# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_merchants_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
            },
        ),
    ]
