# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170208_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('contact_email', models.EmailField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['frist_name'],
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
