# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(default='1', upload_to='/static/img/', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
