# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300, unique=True)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=300)),
                ('vacancies_available', models.CharField(max_length=300)),
                ('posted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobCategories')),
            ],
            options={
                'ordering': ['-posted_on'],
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job postings',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(upload_to='avatars/', verbose_name='Images'),
        ),
    ]
